---
moderation:
  antispam:
    toggle: True
    punishment:
      type: "kick"
      time: 100
    link:
      punishment:
        type: "kick"
        time: 100
      allow_after: 3600
      whitelist: []
      blacklist: []
      greylist: []
    mention:
      punishment:
        type: "kick"
        time: 100
      allow_after: 3600
      rate_limit:
        toggle: True
        time: 600
        mention: 3
      user_toggle: True
      group_toggle: True
      channel_toggle: True
      bot_toggle: True
      whitelist:
        user: []
        group: []
        channel: []
        bot: []
  antiflood:
    toggle: True
    settings: {
      number_messages: 10,
      time_messages: 5
    }
    punishment: {
      type: "kick",
      time: 100
    }