---
moderation:
  antispam:
    toggle: True
    punishment:
      type: "kick"
      time: 100
  antiflood:
    toggle: True
    settings: {
      number_messages: 10,
      time_messages: 5
    }
    punishment: {
      type: "kick",
      time: 100
    }