settings:
  request:
    android:
      app:
        toggle: true
        limit: null
    windows:
      software:
        toggle: true
        limit: 3
      game:
        toggle: true
        limit: 5
      adobe:
        toggle: true
        limit: 3
      daw:
        toggle: true
        limit: 3
    ios:
      app:
        toggle: false
        limit: 3
    macos:
      software:
        toggle: false
        limit: 3
      daw:
        toggle: false
        limit: 3
    cancel_timer: 86400
    cooldown: 30
moderation:
  antispam:
    toggle: true
    punishment:
      type: kick
      time: 100
    whitelist:
      user:
      - 123456789
      group: []
      channel: []
      bot: []
    link:
      punishment:
        type: kick
        time: 100
      allow_after: 3600
      whitelist: []
      blacklist: []
      greylist: []
    mention:
      allow_after: 3600
      per_message: 3
      rate_limit:
        toggle: true
        timespan: 600
        mention: 3
      user:
        toggle: true
        if_not_member: true
        punishment:
          type: kick
          time: 100
      group:
        toggle: true
        if_not_member: null
        punishment:
          type: kick
          time: 100
      channel:
        toggle: true
        if_not_member: null
        punishment:
          type: kick
          time: 100
      bot:
        toggle: true
        if_not_member: null
        punishment:
          type: kick
          time: 100
      whitelist:
        user:
        - 12345678
        group: []
        channel: []
        bot: []
    forward:
      allow_after: 100
      rate_limit:
        timespan: 100
        same_content: 2
        same_source: 2
        same_user: 2
      user:
        toggle: true
        if_not_member: true
        punishment:
          type: kick
          time: 100
      group:
        toggle: true
        if_not_member: null
        punishment:
          type: kick
          time: 100
      channel:
        toggle: true
        if_not_member: null
        punishment:
          type: kick
          time: 100
      bot:
        toggle: true
        if_not_member: null
        punishment:
          type: kick
          time: 100
  antiflood:
    toggle: true
    settings:
      time_messages: 5
      number_messages: 10
    punishment:
      type: kick
      time: 100
