class PrivateConversationState:
    USER_CONVERSATION = 0
    ADMIN_CONVERSATION = 1
    SET_PUNISHMENT_DURATION = 2
    EDIT_ANTISPAM_LINK_LIST = 3
    ADD_ANTISPAM_MENTION_WHITELIST = 4
    REMOVE_ANTISPAM_MENTION_WHITELIST = 5
    NEW_REQUEST = 6


class RequestConversationState:
    REQUEST_NAME = 1
    REQUEST_LINK = 2
    REQUEST_VERSION = 3
    REQUEST_FUNCTIONALITIES = 4
    REQUEST_STEAMTOOLS = 5

    CHECK_REQUEST = 6
    EDIT_NAME = 7
    EDIT_LINK = 8
    EDIT_VERSION = 9
    EDIT_FUNCTIONALITIES = 10
    MAIN_BACKER = 11
