class PrivateConversationState:
    USER_CONVERSATION = 0
    ADMIN_CONVERSATION = 1
    SET_PUNISHMENT_DURATION = 2
    EDIT_ANTISPAM_LINK_LIST = 3
    ADD_ANTISPAM_MENTION_WHITELIST = 4
    REMOVE_ANTISPAM_MENTION_WHITELIST = 5
    NEW_REQUEST = 6
    SET_REQUEST_LIMITATION_DURATION = 7
    SET_REQUEST_LIMITATION_REASON = 8
    SET_REQUEST_LIMITATION_USER = 9
    SET_REQUEST_REJECTION_REASON = 10
    SET_VIEW_REQUEST_LIMITATION_USER = 11
    SET_USER_FOR_REQUEST_ARCHIVE = 12


class RequestConversationState:
    REQUEST_NAME = 1
    REQUEST_LINK = 2
    REQUEST_VERSION = 3
    REQUEST_FUNCTIONALITIES = 4
    REQUEST_STEAMTOOLS = 5
    REQUEST_ARCH = 6
    REQUEST_CATEGORY = 7

    CHECK_REQUEST = 8
    EDIT_NAME = 9
    EDIT_LINK = 10
    EDIT_VERSION = 11
    EDIT_FUNCTIONALITIES = 12
    MAIN_BACKER = 13


class WindowsCategoryState:
    SOFTWARE = 13
    GAME = 14
    DAW = 15
    ADOBE = 16
