class PrivateConversationState:
    USER_CONVERSATION = 0
    ADMIN_CONVERSATION = 1
    USER_REQUEST_WIZARD_SESSION = 2
    SET_PUNISHMENT_DURATION = 3
    EDIT_ANTISPAM_LINK_LIST = 4
    ADD_ANTISPAM_MENTION_WHITELIST = 5
    REMOVE_ANTISPAM_MENTION_WHITELIST = 6
    NEW_REQUEST = 7
    SET_REQUEST_LIMITATION_DURATION = 8
    SET_REQUEST_LIMITATION_REASON = 9
    SET_REQUEST_LIMITATION_USER = 10
    SET_REQUEST_REJECTION_REASON = 11
    SET_USER_FOR_REQUEST_ARCHIVE = 12
    SET_REMINDER_BODY = 13
    SET_REMINDER_DATETIME = 14
